# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d99a132d8dbb778a98beba7dcd0551ca20e27a5ac7338b230536fef478a3a732defbde3284731fe038b1bb1bead9c7502f4e0acbf6f24b72575dfca101d0ec

test:
  secret_key_base: fe757f73daedc06e3e9e1541646f5490e6d8d935f2146d33d25b8d3afe341a75463883f60fda65d18e2b7e8a48fd6b565eead7746530fc13282282b19d401112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
